
const MAIN_PAGE = "MAIN";
const UI = "UI_ACTIONS";

export const FETCH_PRODUCTS = `${MAIN_PAGE}/FETCH_PRODUCTS`;

export const DELETE_PRODUCT = `${MAIN_PAGE}/DELETE_PRODUCT`;

export const SET_IS_LOADING = `${MAIN_PAGE}/SET_IS_LOADING`;

export const SET_IS_ERROR = `${MAIN_PAGE}/SET_IS_ERROR`;

export const ADD_PRODUCT = `${MAIN_PAGE}/ADD_PRODUCT`;

export const EDIT_PRODUCT = `${MAIN_PAGE}/EDIT_PRODUCT`;

export const SET_EDIT = `${MAIN_PAGE}/SET_EDIT`;

export const SET_RESET = `${MAIN_PAGE}/SET_RESET`;

export const CHANGE_NAME = `${MAIN_PAGE}/CHANGE_NAME`;
export const CHANGE_CATEGORY = `${MAIN_PAGE}/CHANGE_CATEGORY`;
export const CHANGE_PRICE = `${MAIN_PAGE}/CHANGE_PRICE`;
export const CHANGE_QUANTITY = `${MAIN_PAGE}/CHANGE_QUANTITY`;
export const CHANGE_DESCRIPTIONS = `${MAIN_PAGE}/CHANGE_DESCRIPTIONS`;
export const CHANGE_IMAGES = `${MAIN_PAGE}/CHANGE_IMAGES`;

// user auth + logic from CARD-LOGIN...
export const SET_LOGIN = `${MAIN_PAGE}/SET_LOGIN`;
export const SET_PASSWORD = `${MAIN_PAGE}/SET_PASSWORD`;
export const SHOW_HIDE_PASSWORD = `${MAIN_PAGE}/SHOW_HIDE_PASSWORD`;
export const SET_ERROR = `${MAIN_PAGE}/SET_ERROR`;
export const CLEAR_ERROR = `${MAIN_PAGE}/CLEAR_ERROR`;
export const SET_USER = `${MAIN_PAGE}/SET_USER`;
export const CLEAR_USER = `${MAIN_PAGE}/CLEAR_USER`;
export const SET_USERS = `${MAIN_PAGE}/SET_USERS`;

export const FETCH_USERS = `${MAIN_PAGE}/FETCH_USERS`;

export const SHOW_OVERLAY = `${UI}/SHOW_OVERLAY`;
export const HIDE_OVERLAY = `${UI}/HIDE_OVERLAY`;
